version: "3.2"
services:
  

  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  accounts-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: "twitchy-accounts-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounts-db
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  auth-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: "twitchy-auth-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth-db
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  chat-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: "twitchy-chat-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-dev
    ports:
      - '5434:5432'
    volumes: 
      - db:/var/lib/postgresql/data

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  db:
    driver: local