version: "3.2"
services:
  chat-service:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: "chat-service-test"
    command:
      - ./test.sh
    depends_on:
      - chat-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=chat-db
      - POSTGRES_DB=chat
      - POSTGRES_PORT=5432
      - PORT=3000
      - MIX_ENV=test
      - JWT_SECRET="test-secret"
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq-test
      - RABBITMQ_PORT=5672
    volumes:
      - .:/opt/app/api
    networks: #For the sake of not leaking anything during tests, we are on a separate network
      - chat_test_network
