FROM bitwalker/alpine-elixir-phoenix:latest

RUN mkdir -p /opt/app/api

WORKDIR /opt/app/api

# Install debian packages
RUN apk add postgresql

# # Install Phoenix packages
# RUN mix local.hex --force
# RUN mix local.rebar --force
# RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

EXPOSE $PORT

# CMD ["bash", "-c", "./entrypoint.sh"]